spring:
  application:
    name: Application_Security_Role_Based
  datasource:
    url: jdbc:mysql://localhost:3306/securitydb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
